import math


# ============================================================
# ALGORITHM 4
# GENERATE_KEY_SEQUENCE
# ============================================================

def generate_key_sequence(
    x: float,
    r2: float,
    rows: int,
    cols: int
):
    """
    Algorithm 4: Generate the key sequence X.

    Input:
        x    - initial chaotic value
        r2   - parameter generated by PARAMETER_INITIALIZATION
        rows - fpart_height
        cols - fpart_width

    Output:
        X - generated key sequence
    """

    # Empty list to store X values
    X = []

    # Total number of values required
    total_values = rows * cols

    # Generate X sequence
    for _ in range(total_values):

        # Generate next chaotic value
        x = (
            (r2 ** 2)
            * (x ** 2 - 5)
            * (1 - r2 * (x ** 2 - 5))
        ) % 1

        # Convert chaotic value to integer between 0 and 255
        key_value = math.floor(
            x * (2 ** 8)
        )

        # Store value in X
        X.append(key_value)

    return X